# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- master

pool:
  vmImage: 'ubuntu-latest'

steps:
- script: echo Hello, world!
  displayName: 'Run a one-line script'

- script: |
    echo Add other tasks to build, test, and deploy your project.
    echo See https://aka.ms/yaml
  displayName: 'Run a multi-line script'
- task: AzureResourceManagerTemplateDeployment@3
  inputs:
    deploymentScope: 'Resource Group'
    azureResourceManagerConnection: 'Visual Studio Ultimate with MSDN(1)(42a2eb5c-8d13-451c-8b50-069e05cdbf86)'
    subscriptionId: '42a2eb5c-8d13-451c-8b50-069e05cdbf86'
    action: 'Create Or Update Resource Group'
    resourceGroupName: 'Customer-Pioneer-Completions-Test2'
    location: 'South Central US'
    templateLocation: 'Linked artifact'
    csmFile: 'RGtemplate.json'
    csmParametersFile: 'RGparameters.json'
    deploymentMode: 'Incremental'

- task: AzureResourceManagerTemplateDeployment@3
  inputs:
    deploymentScope: 'Resource Group'
    azureResourceManagerConnection: 'Visual Studio Ultimate with MSDN(1)(42a2eb5c-8d13-451c-8b50-069e05cdbf86)'
    subscriptionId: '42a2eb5c-8d13-451c-8b50-069e05cdbf86'
    action: 'Create Or Update Resource Group'
    resourceGroupName: 'Customer-Pioneer-Completions-Test2'
    location: 'South Central US'
    templateLocation: 'Linked artifact'
    csmFile: 'ADFtemplate.json'
    csmParametersFile: 'ADFparameters.json'
    deploymentMode: 'Incremental'